I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 77, in script call
    call prepare_battle
  File "game/battlesys/labels/prepare_battle.rpy", line 82, in script call
    call turn_start
  File "game/battlesys/labels/turn_start.rpy", line 9, in script call
    call battle_menu
  File "game/battlesys/labels/menu_battle.rpy", line 16, in script call
    call battle_change_menu
  File "game/battlesys/labels/menu_battle.rpy", line 86, in script call
    call enemy_change
  File "game/battlesys/labels/show_fighters.rpy", line 3, in script
    $ fala = battleState.enemy_team_name + " sent out " + (battleState.enemy_team_current_stats[0]).enemy_name + '!'
  File "game/battlesys/labels/show_fighters.rpy", line 3, in <module>
    $ fala = battleState.enemy_team_name + " sent out " + (battleState.enemy_team_current_stats[0]).enemy_name + '!'
AttributeError: 'NoneType' object has no attribute 'enemy_name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 77, in script call
    call prepare_battle
  File "game/battlesys/labels/prepare_battle.rpy", line 82, in script call
    call turn_start
  File "game/battlesys/labels/turn_start.rpy", line 9, in script call
    call battle_menu
  File "game/battlesys/labels/menu_battle.rpy", line 16, in script call
    call battle_change_menu
  File "game/battlesys/labels/menu_battle.rpy", line 86, in script call
    call enemy_change
  File "game/battlesys/labels/show_fighters.rpy", line 3, in script
    $ fala = battleState.enemy_team_name + " sent out " + (battleState.enemy_team_current_stats[0]).enemy_name + '!'
  File "C:\Users\evald\Downloads\RenPy\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\evald\Downloads\RenPy\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/battlesys/labels/show_fighters.rpy", line 3, in <module>
    $ fala = battleState.enemy_team_name + " sent out " + (battleState.enemy_team_current_stats[0]).enemy_name + '!'
AttributeError: 'NoneType' object has no attribute 'enemy_name'

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.1.23060707
CCbattleSys 1.0
Sat Sep 30 16:39:02 2023
